# Generated by Django 4.2.2 on 2023-08-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_rename_cart_product_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
